---
output:
  pdf_document: default
  html_document:
    df_print: paged
subtitle: SOCAL site M
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load data, eval=TRUE,echo = FALSE, message = FALSE, warning = FALSE}
load('G:/Shared drives/SOCAL_Sonar_Impact/Impact_analysis/2.BinnedData_tables/binnedData_SOCAL_H_sonar_bw.Rdata')
```


```{r func1, eval=TRUE,echo = FALSE, message = FALSE, warning = FALSE}
plot.distr <- function(xid,presAbs,varU,cbase){

# Figure out which rows had detections, which didn't
posRows <- which(presAbs>0)
negRows <- which(presAbs==0)

# Kernel densities
d0 = stats::density(xid[negRows],na.rm = TRUE) # density for negative segments
d1 = stats::density(xid[posRows],na.rm = TRUE) # density for positive segments

x_range = range(c(d0$x,d1$x)) 
d0$y = d0$y/max(d0$y)
d1$y = d1$y/max(d1$y)

{plot(d0, xlim = x_range, lty=1, lwd =1,col=cbase, main = "",xlab =  varU,ylab = 'Normalized counts')
  polygon(d0, xlim = x_range,col=cbase,border = FALSE, main = "",xlab =  "",ylab = "")
  par(new = TRUE)
  plot(d1, xlim = x_range,lwd =2,axes = FALSE, xlab = "", ylab = "", main = "")
  legend("topright", c("Effort","Zc Pres"),lty = 1:1,col = c(cbase,"black"),bty = "n")}
}
```


```{r plot1a,eval=TRUE, message=FALSE, warning=FALSE, results='asis',echo=FALSE,fig.hold = 'hold',fig.width = 4,fig.height = 4,out.width="30%"}
sLag = binData$sLag
sLag[sLag==0] = NA
bwPres = binData$zcPres
bwColor = "darkgray"
plot.distr(sLag/1440,bwPres,"Sonar lag (days)",bwColor)
sProp = binData$sProp
sProp[sProp==0] = NA
plot.distr(sProp,bwPres,"Sonar prop./min",bwColor)
maxRLpp = binData$maxRLpp
maxRLpp[maxRLpp==0] = NA
plot.distr(maxRLpp,bwPres,"Max. RLpp",bwColor)
cumSEL = binData$cumSEL
cumSEL[cumSEL==0] = NA
plot.distr(cumSEL,bwPres,"Cum. SEL",bwColor)
plot.distr(binData$timeofd,bwPres,"Time of day (hrs)",bwColor)
#plot.distr(binData$sunriseLag/60,bwPres,"Hours since sunrise",bwColor)
#plot.distr(binData$sunsetLag/60,bwPres,"Hours since sunset",bwColor)
plot.distr(binData$jd,bwPres,"Julian Date",bwColor)
plot.distr(binData$year,bwPres,"Year",bwColor)
#plot.distr(binData$DN,bwPres,"Day-Night",bwColor)
```

