---
title: "Temporal_Analyses"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Find Time Series Data Files

```{r find files}
library(pracma)

inDir = 'I:/TimeSeries'
distDir = 'I/DataDists'
corrDir = 'I/Autocorrelation'

fileList = list.files(path=inDir,pattern='*.csv',full.names=TRUE,recursive=FALSE,include.dirs=FALSE,no..=TRUE)


```

## Import one data file at a time and plot data distribution and autocorrelation


```{r load,plot,save}
for (i in 1:numel(fileList)){  # for each species file


thisCT = data.frame(read.csv(fileList[i]))  # load file
attribs = attributes(thisCT)  # find names of sites (all columns but first)
sites = attribs$names[2:numel(attribs$names)]

for (j in 1:numel(sites)){
  
  thisSite = thisCT[,j+1]
  saveName = paste(sites[j],"_DataDist.png",sep="")
    
  png(saveName)
  hist(thisSite)
  dev.off()
  
  
}
  
  
}
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
